import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "../providers";
import UserInitializer from "../hooks/userInitializer";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/auth";
import { Toaster } from "@ui/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    
  return (
    <html lang="en">
        <body className={`box-border ${geistSans.variable} ${geistMono.variable}`}>
          <Providers>
            <UserInitializer />
            <div>
              {children}
            </div>
            <Toaster />
        </Providers>
        </body>
    </html>
  );
}
